#ifndef SLANGUAGEMANAGER_GLOBAL_H
#define SLANGUAGEMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SLANGUAGEMANAGER_LIBRARY)
#  define SLANGUAGEMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SLANGUAGEMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SLANGUAGEMANAGER_GLOBAL_H
